-- 0001_init.sql — PostgreSQL baseline schema for tela.
--
-- This is a SQUASH of the original SQLite migrations 0001–0018, rewritten for
-- PostgreSQL and collapsed into one baseline. The SQLite history was discarded
-- during the SQLite→Postgres switch (the live DB held no data worth keeping);
-- this file is the new starting point. Forward-only from here: never edit an
-- applied migration, add NNNN_name.sql for the next change.
--
-- Conventions carried over from the SQLite era and DELIBERATELY KEPT:
--   * Datetimes are TEXT in the 'YYYY-MM-DD HH:MM:SS' (UTC, no 'Z') wire
--     format, not timestamptz. The whole backend reads them as Go strings and
--     compares them lexicographically; the frontend parses the same format
--     (parseSqliteTs). Keeping TEXT means zero churn in the read paths. The
--     modernc-SQLite reason for TEXT (RFC3339 affinity coercion) is gone, but
--     the wire-format contract remains. tela_now() supplies the default.
--   * Booleans are INTEGER 0/1 (is_active, resolved, include_descendants, …) —
--     Go scans them as ints / via database/sql's bool converter, unchanged.
--   * Surrogate keys are BIGINT IDENTITY (was INTEGER PRIMARY KEY AUTOINCREMENT).
--     Inserts use RETURNING id (Postgres has no LastInsertId / rowid).
--   * Binary blobs are BYTEA (was BLOB): Yjs payloads, diagram/image bytes.
--
-- Search: there is intentionally NO full-text index here. The SQLite FTS5
-- virtual table + sync triggers + tela_strip_excalidraw UDF were removed; the
-- /search endpoints run a placeholder ILIKE for now. The real instant-search +
-- semantic-refinement design is captured in docs/search.md and will land as a
-- later migration (tsvector / pg_trgm / pgvector all live in this same DB).

-- tela_now() is the canonical 'YYYY-MM-DD HH:MM:SS' UTC timestamp used as the
-- DEFAULT for every datetime column, mirroring the old SQLite datetime('now').
-- Go's nowStamp() emits the identical format for values written from code.
CREATE FUNCTION tela_now() RETURNS text
  LANGUAGE sql
  AS $$ SELECT to_char((now() AT TIME ZONE 'UTC'), 'YYYY-MM-DD HH24:MI:SS') $$;

-- ── Identity ────────────────────────────────────────────────────────────────

CREATE TABLE users (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username          TEXT NOT NULL UNIQUE,
  password_hash     TEXT NOT NULL,
  is_instance_admin INTEGER NOT NULL DEFAULT 0,
  is_active         INTEGER NOT NULL DEFAULT 1,
  -- email is nullable: legacy/bootstrap username-only rows skip the email gate.
  -- Stored lowercased; the partial unique index enforces one account per address.
  email             TEXT,
  email_verified_at TEXT,
  created_at        TEXT NOT NULL DEFAULT tela_now(),
  updated_at        TEXT NOT NULL DEFAULT tela_now(),
  CHECK (length(username) BETWEEN 1 AND 64)
);

CREATE UNIQUE INDEX idx_users_email ON users(email) WHERE email IS NOT NULL;

CREATE TABLE sessions (
  id           TEXT PRIMARY KEY,
  user_id      BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  expires_at   TEXT NOT NULL,
  last_seen_at TEXT NOT NULL,
  user_agent   TEXT NOT NULL DEFAULT '',
  created_at   TEXT NOT NULL DEFAULT tela_now()
);

CREATE INDEX idx_sessions_user ON sessions(user_id);
CREATE INDEX idx_sessions_expires ON sessions(expires_at);

-- Email verify / password-reset tokens. Stored only as a SHA-256 hash — the raw
-- token lives solely in the emailed link.
CREATE TABLE email_tokens (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  kind        TEXT NOT NULL CHECK (kind IN ('verify','reset')),
  token_hash  TEXT NOT NULL UNIQUE,
  expires_at  TEXT NOT NULL,
  consumed_at TEXT,
  created_at  TEXT NOT NULL DEFAULT tela_now()
);

CREATE INDEX idx_email_tokens_user ON email_tokens(user_id);
CREATE INDEX idx_email_tokens_expires ON email_tokens(expires_at);

-- ── Orgs / groups (multi-tenant grouping over per-space membership) ───────────

CREATE TABLE orgs (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       TEXT NOT NULL,
  slug       TEXT NOT NULL UNIQUE,
  created_at TEXT NOT NULL DEFAULT tela_now(),
  updated_at TEXT NOT NULL DEFAULT tela_now(),
  CHECK (length(name) BETWEEN 1 AND 200)
);

CREATE TABLE org_members (
  org_id     BIGINT NOT NULL REFERENCES orgs(id) ON DELETE CASCADE,
  user_id    BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  org_role   TEXT NOT NULL CHECK (org_role IN ('admin','member')),
  created_at TEXT NOT NULL DEFAULT tela_now(),
  updated_at TEXT NOT NULL DEFAULT tela_now(),
  PRIMARY KEY (org_id, user_id)
);

CREATE INDEX idx_org_members_user ON org_members(user_id);

-- Instance-admin-curated auto-join by verified email domain. Auto-join is
-- member-only (the per-domain role choice was dropped in the SQLite 0017 pass).
CREATE TABLE org_email_domains (
  domain     TEXT PRIMARY KEY,
  org_id     BIGINT NOT NULL REFERENCES orgs(id) ON DELETE CASCADE,
  created_at TEXT NOT NULL DEFAULT tela_now()
);

CREATE INDEX idx_org_email_domains_org ON org_email_domains(org_id);

-- A group is the third grantable principal: nests under exactly one org.
CREATE TABLE groups (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  org_id     BIGINT NOT NULL REFERENCES orgs(id) ON DELETE CASCADE,
  name       TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT tela_now(),
  updated_at TEXT NOT NULL DEFAULT tela_now(),
  CHECK (length(name) BETWEEN 1 AND 200),
  UNIQUE (org_id, name)
);

CREATE INDEX idx_groups_org ON groups(org_id);

-- Group membership ⊆ org membership, enforced by the trigger below.
CREATE TABLE group_members (
  group_id   BIGINT NOT NULL REFERENCES groups(id) ON DELETE CASCADE,
  user_id    BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at TEXT NOT NULL DEFAULT tela_now(),
  PRIMARY KEY (group_id, user_id)
);

CREATE INDEX idx_group_members_user ON group_members(user_id);

-- Containment invariant (1): you can only add an org member to that org's group.
-- (SQLite RAISE(ABORT) → PL/pgSQL RAISE EXCEPTION.)
CREATE FUNCTION group_members_require_org_member() RETURNS trigger
  LANGUAGE plpgsql AS $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM org_members om
      JOIN groups g ON g.id = NEW.group_id
     WHERE om.org_id = g.org_id AND om.user_id = NEW.user_id
  ) THEN
    RAISE EXCEPTION 'group member must be a member of the group org';
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER group_members_require_org_member
  BEFORE INSERT ON group_members
  FOR EACH ROW EXECUTE FUNCTION group_members_require_org_member();

-- ── Spaces + pages ────────────────────────────────────────────────────────────

CREATE TABLE spaces (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name             TEXT NOT NULL,
  slug             TEXT NOT NULL UNIQUE,
  -- personal_user_id labels a user's private one-member space (provisioning
  -- idempotency); org_id is the owning org (NULL for personal/legacy spaces).
  personal_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  org_id           BIGINT REFERENCES orgs(id) ON DELETE SET NULL,
  created_at       TEXT NOT NULL DEFAULT tela_now(),
  updated_at       TEXT NOT NULL DEFAULT tela_now()
);

CREATE UNIQUE INDEX idx_spaces_personal_user
  ON spaces(personal_user_id) WHERE personal_user_id IS NOT NULL;
CREATE INDEX idx_spaces_org ON spaces(org_id);

CREATE TABLE pages (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  space_id   BIGINT NOT NULL REFERENCES spaces(id) ON DELETE CASCADE,
  parent_id  BIGINT REFERENCES pages(id) ON DELETE CASCADE,
  title      TEXT NOT NULL,
  body       TEXT NOT NULL DEFAULT '',
  position   INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT tela_now(),
  updated_at TEXT NOT NULL DEFAULT tela_now()
);

CREATE INDEX idx_pages_space_parent_pos ON pages(space_id, parent_id, position);

-- Denormalized outgoing wikilinks. No FK to pages on purpose: an orphan
-- target_id is how the frontend detects a broken link; last_known_title caches
-- the label captured at deletion time.
CREATE TABLE page_links (
  source_id        BIGINT NOT NULL,
  target_id        BIGINT NOT NULL,
  last_known_title TEXT NOT NULL DEFAULT '',
  created_at       TEXT NOT NULL DEFAULT tela_now(),
  updated_at       TEXT NOT NULL DEFAULT tela_now(),
  PRIMARY KEY (source_id, target_id)
);

CREATE INDEX idx_page_links_target ON page_links(target_id);

-- ── Membership / grants ───────────────────────────────────────────────────────

-- Canonical direct-user grants (last-owner / self-leave safeguards live in the API).
CREATE TABLE space_members (
  space_id   BIGINT NOT NULL REFERENCES spaces(id) ON DELETE CASCADE,
  user_id    BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  role       TEXT NOT NULL CHECK (role IN ('owner','editor','viewer')),
  created_at TEXT NOT NULL DEFAULT tela_now(),
  updated_at TEXT NOT NULL DEFAULT tela_now(),
  PRIMARY KEY (space_id, user_id)
);

CREATE INDEX idx_space_members_user ON space_members(user_id);

-- Polymorphic grant edge for org/group principals. principal_id cannot carry a
-- real FK (it points at orgs OR groups); cleanup is handled in the API layer.
CREATE TABLE space_grants (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  space_id       BIGINT NOT NULL REFERENCES spaces(id) ON DELETE CASCADE,
  principal_kind TEXT NOT NULL CHECK (principal_kind IN ('user','org','group')),
  principal_id   BIGINT NOT NULL,
  role           TEXT NOT NULL CHECK (role IN ('owner','editor','viewer')),
  created_at     TEXT NOT NULL DEFAULT tela_now(),
  updated_at     TEXT NOT NULL DEFAULT tela_now(),
  UNIQUE (space_id, principal_kind, principal_id)
);

CREATE INDEX idx_space_grants_space ON space_grants(space_id);
CREATE INDEX idx_space_grants_principal ON space_grants(principal_kind, principal_id);

-- Owner invariant (defense in depth behind the API checks): org/group grants can
-- never be 'owner'. Covers INSERT and UPDATE in one trigger function.
CREATE FUNCTION space_grants_no_principal_owner() RETURNS trigger
  LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.principal_kind IN ('org','group') AND NEW.role = 'owner' THEN
    RAISE EXCEPTION 'org/group grants cannot have role owner';
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER space_grants_no_principal_owner
  BEFORE INSERT OR UPDATE ON space_grants
  FOR EACH ROW EXECUTE FUNCTION space_grants_no_principal_owner();

-- Containment invariant (2): leaving an org leaves all of its groups.
CREATE FUNCTION org_members_cascade_groups() RETURNS trigger
  LANGUAGE plpgsql AS $$
BEGIN
  DELETE FROM group_members
   WHERE user_id = OLD.user_id
     AND group_id IN (SELECT id FROM groups WHERE org_id = OLD.org_id);
  RETURN OLD;
END;
$$;

CREATE TRIGGER org_members_cascade_groups
  AFTER DELETE ON org_members
  FOR EACH ROW EXECUTE FUNCTION org_members_cascade_groups();

-- Single source of truth for "who can access which space, at what role" =
-- direct user grants ∪ org-mediated ∪ group-mediated. Callers needing the
-- single effective role pick the max by precedence; access gates use DISTINCT.
CREATE VIEW space_access (space_id, user_id, role) AS
  SELECT space_id, user_id, role FROM space_members
  UNION ALL
  SELECT sg.space_id, om.user_id, sg.role
    FROM space_grants sg
    JOIN org_members om ON om.org_id = sg.principal_id
   WHERE sg.principal_kind = 'org'
  UNION ALL
  SELECT sg.space_id, gm.user_id, sg.role
    FROM space_grants sg
    JOIN group_members gm ON gm.group_id = sg.principal_id
   WHERE sg.principal_kind = 'group';

-- ── Collaboration / content sidecars ──────────────────────────────────────────

-- Comments: SQL-only, decoupled from body/Yjs. Flat depth-1 threading; soft
-- delete via deleted_at; partial indexes filter deleted rows for the hot reads.
CREATE TABLE comments (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  page_id       BIGINT NOT NULL REFERENCES pages(id) ON DELETE CASCADE,
  parent_id     BIGINT REFERENCES comments(id) ON DELETE CASCADE,
  author_id     BIGINT NOT NULL REFERENCES users(id),
  body          TEXT NOT NULL,
  anchor_prefix TEXT,
  anchor_exact  TEXT,
  anchor_suffix TEXT,
  resolved      INTEGER NOT NULL DEFAULT 0,
  resolved_at   TEXT,
  resolved_by   BIGINT REFERENCES users(id),
  created_at    TEXT NOT NULL,
  updated_at    TEXT NOT NULL,
  deleted_at    TEXT
);

CREATE INDEX idx_comments_page ON comments(page_id) WHERE deleted_at IS NULL;
CREATE INDEX idx_comments_parent ON comments(parent_id) WHERE deleted_at IS NULL;

-- Per-save markdown revisions. author_id nullable; byte_size caches length(body).
CREATE TABLE page_revisions (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  page_id    BIGINT NOT NULL REFERENCES pages(id) ON DELETE CASCADE,
  body       TEXT NOT NULL,
  title      TEXT NOT NULL,
  author_id  BIGINT REFERENCES users(id),
  source     TEXT NOT NULL,
  byte_size  INTEGER NOT NULL,
  created_at TEXT NOT NULL
);

CREATE INDEX idx_page_revisions_page_created ON page_revisions(page_id, created_at DESC);

-- Public share tokens. password_hash NULL = open; argon2id-encoded otherwise.
CREATE TABLE share_links (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  token               TEXT UNIQUE NOT NULL,
  page_id             BIGINT NOT NULL REFERENCES pages(id) ON DELETE CASCADE,
  include_descendants INTEGER NOT NULL DEFAULT 0,
  password_hash       TEXT,
  created_by          BIGINT NOT NULL REFERENCES users(id),
  created_at          TEXT NOT NULL DEFAULT tela_now(),
  expires_at          TEXT,
  revoked_at          TEXT
);

CREATE INDEX idx_share_links_page_active ON share_links(page_id) WHERE revoked_at IS NULL;
CREATE INDEX idx_share_links_token ON share_links(token);

-- Excalidraw PNG sidecars (content-addressed by scene_hash). PNG bytes in BYTEA.
CREATE TABLE page_diagrams (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  page_id    BIGINT NOT NULL REFERENCES pages(id) ON DELETE CASCADE,
  scene_hash TEXT NOT NULL,
  png        BYTEA NOT NULL,
  byte_size  INTEGER NOT NULL,
  created_at TEXT NOT NULL DEFAULT tela_now(),
  UNIQUE (page_id, scene_hash)
);

CREATE INDEX idx_page_diagrams_page ON page_diagrams(page_id);

-- Uploaded image bytes (content-addressed by sha256). Served public + immutable.
CREATE TABLE page_images (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  page_id      BIGINT NOT NULL REFERENCES pages(id) ON DELETE CASCADE,
  content_hash TEXT NOT NULL,
  mime         TEXT NOT NULL,
  data         BYTEA NOT NULL,
  byte_size    INTEGER NOT NULL,
  created_at   TEXT NOT NULL DEFAULT tela_now(),
  UNIQUE (page_id, content_hash)
);

CREATE INDEX idx_page_images_page ON page_images(page_id);

-- Opaque Yjs update/snapshot persistence (server is a dumb relay+persister).
CREATE TABLE page_yjs_updates (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  page_id    BIGINT NOT NULL REFERENCES pages(id) ON DELETE CASCADE,
  seq        INTEGER NOT NULL,
  payload    BYTEA NOT NULL,
  created_at TEXT NOT NULL DEFAULT tela_now(),
  UNIQUE (page_id, seq)
);

CREATE INDEX idx_page_yjs_updates_page_seq ON page_yjs_updates(page_id, seq DESC);

CREATE TABLE page_yjs_snapshots (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  page_id    BIGINT NOT NULL REFERENCES pages(id) ON DELETE CASCADE,
  seq        INTEGER NOT NULL,
  state      BYTEA NOT NULL,
  created_at TEXT NOT NULL DEFAULT tela_now(),
  UNIQUE (page_id, seq)
);

CREATE INDEX idx_page_yjs_snapshots_page_seq ON page_yjs_snapshots(page_id, seq DESC);

-- ── API keys (bearer auth for headless agents / MCP) ──────────────────────────

CREATE TABLE api_keys (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id      BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  name         TEXT NOT NULL,
  key_prefix   TEXT NOT NULL,
  key_hmac     TEXT NOT NULL,
  scope        TEXT NOT NULL CHECK (scope IN ('read','write','admin')),
  space_id     BIGINT REFERENCES spaces(id) ON DELETE CASCADE,
  last_used_at TEXT,
  expires_at   TEXT,
  created_at   TEXT NOT NULL DEFAULT tela_now(),
  revoked_at   TEXT
);

CREATE UNIQUE INDEX idx_api_keys_hmac ON api_keys(key_hmac);
CREATE INDEX idx_api_keys_user ON api_keys(user_id) WHERE revoked_at IS NULL;

CREATE TABLE api_key_audit (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  api_key_id  BIGINT NOT NULL REFERENCES api_keys(id) ON DELETE CASCADE,
  method      TEXT NOT NULL,
  path        TEXT NOT NULL,
  status_code INTEGER NOT NULL,
  ts          TEXT NOT NULL DEFAULT tela_now()
);

CREATE INDEX idx_api_key_audit_key_ts ON api_key_audit(api_key_id, ts);

-- ── Misc ──────────────────────────────────────────────────────────────────────

-- Developer-facing meta-feedback (write-only in v0). Provenance columns survive
-- user/key deletion via ON DELETE SET NULL.
CREATE TABLE feedback (
  id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at            TEXT NOT NULL DEFAULT tela_now(),
  created_by_user_id    BIGINT REFERENCES users(id) ON DELETE SET NULL,
  created_by_api_key_id BIGINT REFERENCES api_keys(id) ON DELETE SET NULL,
  subject               TEXT NOT NULL CHECK (length(subject) BETWEEN 1 AND 200),
  body                  TEXT NOT NULL CHECK (length(body) BETWEEN 1 AND 8000)
);

CREATE INDEX idx_feedback_created_at ON feedback(created_at DESC);

-- Membership/grant/auto-join/org audit trail (instance-admin read surface).
CREATE TABLE access_audit (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  action        TEXT NOT NULL,
  target_kind   TEXT NOT NULL,
  target_id     BIGINT,
  detail        TEXT NOT NULL DEFAULT '',
  created_at    TEXT NOT NULL DEFAULT tela_now()
);

CREATE INDEX idx_access_audit_created ON access_audit(created_at);
