-- 0002_rag.sql — RAG foundation: pgvector + the derived chunk/embedding index.
--
-- This is the semantic half of search (see docs/search.md). It lays only the
-- FOUNDATION: enable the vector extension and create the page_chunks index
-- table. The chunker, the embed pipeline, and the hybrid query are built on top
-- of this, iteratively — they are not in this migration.
--
-- Sticky invariant (do not break): page_chunks is a DISPOSABLE, derived cache
-- of pages. It is fully rebuildable from pages.body and carries NO authorization
-- state of its own. Every retrieval query authorizes by joining the LIVE pages
-- row through space_access — never denormalize permissions onto a chunk. This is
-- the anti-leak invariant: permissions and vectors share one store and one query.

CREATE EXTENSION IF NOT EXISTS vector;

-- One row per (page, chunk). embedding is nullable so a chunk can exist before
-- it is embedded — embedding is an external network op (Ollama on tardis),
-- driven off the write path, not a SQL trigger. content_hash lets the embed
-- pipeline skip unchanged chunks on re-index.
CREATE TABLE page_chunks (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  page_id      BIGINT NOT NULL REFERENCES pages(id) ON DELETE CASCADE,
  ord          INTEGER NOT NULL,            -- 0-based chunk order within the page
  heading_path TEXT NOT NULL DEFAULT '',    -- citation, e.g. 'Title > H2 > H3'
  content      TEXT NOT NULL,               -- the embedded text (excalidraw-stripped; may carry a contextual prefix)
  content_hash TEXT NOT NULL,               -- hash of content; skip re-embed when unchanged
  embedding    vector(1024),                -- mxbai-embed-large dims; NULL until embedded
  created_at   TEXT NOT NULL DEFAULT tela_now(),
  updated_at   TEXT NOT NULL DEFAULT tela_now()
);

-- The natural (page, ord) ordering; its leftmost prefix also serves page_id
-- lookups and the ON DELETE CASCADE.
CREATE UNIQUE INDEX idx_page_chunks_page_ord ON page_chunks(page_id, ord);

-- No ANN index (HNSW / IVFFlat) yet, on purpose. At a team-wiki's scale an
-- exact sequential scan is fast and avoids ANN recall loss; the index choice +
-- params are an open decision to make against real data (RAG journey doc). Add
-- it in a later migration when a seq scan stops being enough.
