-- 0007_notifications.sql — per-user notifications ("something happened you
-- should know about"). See docs/notifications.md for the full model.
--
-- Generic over its subject (subject_kind/subject_id, like access_audit) so any
-- entity can be the thing you're notified about, and over its type (text, not an
-- enum) so adding an event kind is data, not DDL. `data` is a small denormalized
-- render payload (page title, actor name) so the inbox renders without N+1 and
-- survives the source being edited/deleted. dedup_key + its partial unique index
-- make re-emits idempotent (a page re-saved with the same @mention notifies once).

CREATE TABLE notifications (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id      BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  type         TEXT   NOT NULL,
  actor_id     BIGINT REFERENCES users(id) ON DELETE SET NULL,
  subject_kind TEXT   NOT NULL,
  subject_id   BIGINT NOT NULL,
  space_id     BIGINT REFERENCES spaces(id) ON DELETE CASCADE,
  data         JSONB  NOT NULL DEFAULT '{}',
  dedup_key    TEXT,
  read_at      TEXT,
  created_at   TEXT   NOT NULL DEFAULT tela_now()
);

CREATE INDEX idx_notifications_user_created ON notifications(user_id, created_at DESC);
CREATE INDEX idx_notifications_user_unread ON notifications(user_id) WHERE read_at IS NULL;
CREATE UNIQUE INDEX uq_notifications_dedup ON notifications(user_id, dedup_key) WHERE dedup_key IS NOT NULL;
