-- 0009_change_log.sql — append-only per-space change feed (sync §4 D10, Phase 5).
--
-- `updated_at` is second-granularity TEXT and non-monotonic across pages, so it
-- cannot be a sync cursor: a client polling "what changed since X" can't range
-- over it without missing or re-seeing rows. This append-only log gives a
-- monotonic BIGINT `seq` (the cursor) per write, so a client pulls deltas
-- (`seq > cursor`) instead of re-scanning the whole space. Powers GET /api/changes
-- now and the push-based tela-own engine later.
--
-- page_id is intentionally NOT a foreign key: a row recording a page's deletion
-- must outlive the page (a client polling for deletes needs to see them). Pages
-- soft-delete anyway, so there is no hard row to cascade from.
--
-- Caveat (acceptable this phase): `seq` is a bare IDENTITY, so under concurrent
-- transactions a higher seq can become visible before a lower one commits — a
-- client that advances its cursor in that window could skip the lagging row. The
-- window is tiny for a wiki's write rate; the engine phase hardens it (commit-
-- ordered cursor / overlap re-poll).

CREATE TABLE change_log (
  seq        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  space_id   BIGINT NOT NULL REFERENCES spaces(id) ON DELETE CASCADE,
  page_id    BIGINT NOT NULL,
  action     TEXT NOT NULL CHECK (action IN ('created','updated','moved','deleted')),
  created_at TEXT NOT NULL DEFAULT tela_now()
);

-- The hot query is the per-space range scan `WHERE space_id = $1 AND seq > $2`.
CREATE INDEX idx_change_log_space_seq ON change_log(space_id, seq);
