-- 0029_ask_log.sql — log "ask your docs" questions + retrieval confidence so the
-- questions the corpus COULDN'T answer surface as a content roadmap (knowledge
-- gaps). One row per /api/rag/ask call, written best-effort off the ask path.
--
-- hit_count = chunks retrieved; top_score = best fused score (0 when nothing
-- retrieved); answered = whether anything was retrieved at all (0/1, SQLite-era
-- boolean convention). A question with hit_count 0 is an unambiguous gap; the
-- aggregate view groups repeats so "asked 5×, answered 0×" rises to the top.
--
-- Reading the log is admin-gated (it holds users' questions); logging can be
-- disabled instance-wide via TELA_RAG_LOG_ASKS=0.

CREATE TABLE ask_log (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    BIGINT REFERENCES users(id)  ON DELETE SET NULL,
  space_id   BIGINT REFERENCES spaces(id) ON DELETE SET NULL,  -- ask scope; NULL = across all readable spaces
  question   TEXT NOT NULL,
  hit_count  INTEGER NOT NULL DEFAULT 0,
  top_score  DOUBLE PRECISION NOT NULL DEFAULT 0,
  answered   INTEGER NOT NULL DEFAULT 0,                       -- 0/1: did retrieval return anything
  created_at TEXT NOT NULL DEFAULT tela_now()
);

CREATE INDEX idx_ask_log_created ON ask_log(created_at DESC);
