-- 0036_file_chunks.sql — the file half of the document RAG index. Sibling to
-- page_chunks (0002/0003): identical shape, but a chunk belongs to a space_file
-- (its extracted PDF/plaintext text) instead of a page, so attachments become
-- searchable + answerable by the same hybrid retrieval. Kept a SEPARATE table
-- (not a generalized page_chunks) so the deployed page index is untouched; the
-- two are UNIONed at query time.
--
-- Like page_chunks, this carries NO space_id — retrieval authorizes through the
-- LIVE space_files row (the anti-leak invariant: a chunk can never out-scope its
-- file), and ON DELETE CASCADE drops a file's chunks with the file.
--
-- id starts high (2^40) so a file-chunk id never collides with a page-chunk id;
-- read_chunk routes a chunk id to the right table by that range. content_tsv is a
-- generated STORED column (lexical half), exactly as page_chunks (migration 0003).
CREATE TABLE file_chunks (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1099511627776) PRIMARY KEY,
  space_file_id BIGINT NOT NULL REFERENCES space_files(id) ON DELETE CASCADE,
  ord           INTEGER NOT NULL,
  heading_path  TEXT NOT NULL DEFAULT '',
  content       TEXT NOT NULL,
  content_hash  TEXT NOT NULL,
  embedding     vector(1024),
  embed_model   TEXT,
  content_tsv   tsvector GENERATED ALWAYS AS (to_tsvector('english', content)) STORED,
  created_at    TEXT NOT NULL DEFAULT tela_now(),
  updated_at    TEXT NOT NULL DEFAULT tela_now()
);

CREATE UNIQUE INDEX idx_file_chunks_file_ord ON file_chunks(space_file_id, ord);
CREATE INDEX idx_file_chunks_content_tsv ON file_chunks USING GIN (content_tsv);
