-- 0048_atlas.sql — atlas: source-grounded, coverage-audited doc generation.
--
-- Brings the standalone atlas engine natively into tela (see docs/atlas.md). The
-- engine is lifted verbatim (backend/internal/atlas); only its persistence seam
-- (EngineStore) changes from SQLite to these Postgres tables.
--
-- Collapsed vs standalone atlas: no `connections` (instance LLM), no `projects`
-- (the managed space IS the project — freshness lives on the source), no
-- `destinations` (the bound space is the output). A space is "atlas-managed" when
-- it has an atlas_sources row — derived, not a column (don't over-engineer the
-- marker). Run-scoped ingestion tables are disposable: ON DELETE CASCADE from
-- atlas_runs, fully rebuildable by re-running.

-- A thing to document, bound to a space (and optionally a top-dir parent page).
-- Binding a row makes the space atlas-managed. Freshness (auto_update/cadence)
-- lives here since there is no project. secret_id is the future git/jira credential
-- (Phase 5); NULL = public/no-auth.
CREATE TABLE atlas_sources (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  space_id        BIGINT NOT NULL REFERENCES spaces(id) ON DELETE CASCADE,
  parent_page_id  BIGINT REFERENCES pages(id) ON DELETE SET NULL,  -- top-dir for a multi-source space; NULL = space root
  type            TEXT NOT NULL,                       -- 'git' | 'jira'
  location        TEXT NOT NULL,                       -- git URL/path | jira base
  name            TEXT NOT NULL DEFAULT '',            -- optional subtree label
  ref             TEXT NOT NULL DEFAULT '',            -- last pinned commit/revision
  branch          TEXT NOT NULL DEFAULT '',
  subpath         TEXT NOT NULL DEFAULT '',
  include         TEXT NOT NULL DEFAULT '',            -- comma-sep globs
  exclude         TEXT NOT NULL DEFAULT '',
  secret_id       BIGINT,                              -- git/jira credential (Phase 5); NULL = public
  auto_update     INTEGER NOT NULL DEFAULT 1,          -- 0/1; freshness scheduler gate
  cadence         TEXT NOT NULL DEFAULT 'daily',       -- 'hourly'|'daily'|'weekly'|'monthly'|''=off
  last_refresh_at TEXT NOT NULL DEFAULT '',            -- '' = never (due now)
  created_at      TEXT NOT NULL DEFAULT tela_now()
);
CREATE INDEX idx_atlas_sources_space ON atlas_sources(space_id);

-- One pipeline execution over a source.
CREATE TABLE atlas_runs (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_id      BIGINT NOT NULL REFERENCES atlas_sources(id) ON DELETE CASCADE,
  kind           TEXT NOT NULL DEFAULT 'full',         -- 'full' | 'delta'
  baseline_id    BIGINT NOT NULL DEFAULT 0,            -- delta: the prior run diffed against
  changeset_json TEXT NOT NULL DEFAULT '',             -- delta: core.ChangeSet as JSON
  status         TEXT NOT NULL,                        -- pending|running|done|failed|canceled
  stage          TEXT NOT NULL DEFAULT '',
  err            TEXT NOT NULL DEFAULT '',
  coverage_json  TEXT NOT NULL DEFAULT '',             -- core.Coverage, set by validate/repair
  stats_json     TEXT NOT NULL DEFAULT '',             -- core.RunStats, set at publish
  started_at     TEXT NOT NULL DEFAULT tela_now(),
  finished_at    TEXT NOT NULL DEFAULT ''
);
CREATE INDEX idx_atlas_runs_source ON atlas_runs(source_id);
CREATE INDEX idx_atlas_runs_status ON atlas_runs(status);

-- Full per-run event log: durable SSE replay of run progress.
CREATE TABLE atlas_run_events (
  id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id  BIGINT NOT NULL REFERENCES atlas_runs(id) ON DELETE CASCADE,
  stage   TEXT NOT NULL,
  level   TEXT NOT NULL,                                -- info|warn|error
  msg     TEXT NOT NULL,
  cur     INTEGER NOT NULL DEFAULT 0,
  total   INTEGER NOT NULL DEFAULT 0,
  at      TEXT NOT NULL DEFAULT tela_now()
);
CREATE INDEX idx_atlas_run_events_run ON atlas_run_events(run_id);

-- Run-scoped ingestion artifacts (disposable) -------------------------------

CREATE TABLE atlas_files (
  id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id  BIGINT NOT NULL REFERENCES atlas_runs(id) ON DELETE CASCADE,
  path    TEXT NOT NULL,
  lang    TEXT NOT NULL,
  size    BIGINT NOT NULL,
  lines   INTEGER NOT NULL,
  hash    TEXT NOT NULL DEFAULT ''                      -- content SHA256 (hex); delta-reuse safety
);
CREATE INDEX idx_atlas_files_run ON atlas_files(run_id);

-- The deterministic surface inventory (the spine / completeness checklist).
CREATE TABLE atlas_symbols (
  id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id  BIGINT NOT NULL REFERENCES atlas_runs(id) ON DELETE CASCADE,
  kind    TEXT NOT NULL,
  name    TEXT NOT NULL,
  file    TEXT NOT NULL,
  line    INTEGER NOT NULL,
  detail  TEXT NOT NULL DEFAULT ''
);
CREATE INDEX idx_atlas_symbols_run ON atlas_symbols(run_id);

-- Source-code chunks. embedding persists for resume/delta reuse; the generation
-- retriever (dense+BM25 fusion) is rebuilt IN-MEMORY from these rows (lifted
-- engine.BuildRetriever), so there is deliberately NO content_tsv here — SQL FTS
-- is not on this path.
CREATE TABLE atlas_chunks (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id      BIGINT NOT NULL REFERENCES atlas_runs(id) ON DELETE CASCADE,
  file        TEXT NOT NULL,
  start_line  INTEGER NOT NULL,
  end_line    INTEGER NOT NULL,
  kind        TEXT NOT NULL,
  symbol      TEXT NOT NULL DEFAULT '',
  text        TEXT NOT NULL,
  embedding   vector(1024)                               -- NULL until embedded (same dim as page_chunks)
);
CREATE INDEX idx_atlas_chunks_run ON atlas_chunks(run_id);

-- The engine's working pages (planning + incremental body across draft/refine/
-- repair, with resume rehydration state). The FINAL published docs are ordinary
-- tela `pages` rows in the bound space; the publish stage (Phase 2) upserts these
-- into pages via the page core funcs and records the mapping in atlas_page_map.
CREATE TABLE atlas_pages (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id           BIGINT NOT NULL REFERENCES atlas_runs(id) ON DELETE CASCADE,
  ord              INTEGER NOT NULL,
  kind             TEXT NOT NULL,                        -- 'narrative' | 'reference'
  title            TEXT NOT NULL,
  slug             TEXT NOT NULL,
  summary          TEXT NOT NULL DEFAULT '',
  topics_json      TEXT NOT NULL DEFAULT '',             -- []string (resume)
  spine_kinds_json TEXT NOT NULL DEFAULT '',             -- []SpineKind (resume)
  body             TEXT NOT NULL DEFAULT ''
);
CREATE INDEX idx_atlas_pages_run ON atlas_pages(run_id);

-- Upsert bookkeeping: remembers the tela page created for a (source, slug) so
-- re-runs update in place instead of duplicating (atlas's page_deliveries,
-- collapsed to one in-process destination). The per-source root uses slug
-- '__root__'. Keyed by source so multiple sources in a space never collide.
CREATE TABLE atlas_page_map (
  source_id BIGINT NOT NULL REFERENCES atlas_sources(id) ON DELETE CASCADE,
  slug      TEXT NOT NULL,
  page_id   BIGINT NOT NULL REFERENCES pages(id) ON DELETE CASCADE,
  PRIMARY KEY (source_id, slug)
);
