-- 0060_org_invites.sql — pending email invitations to an organization, for
-- self-serve teams. An org admin invites a teammate by email; the raw token
-- lives only in the emailed link (we store its hash, mirroring email_tokens).
-- The invitee joins on accept (logged-in, matching verified email) or auto-joins
-- when they verify a fresh signup with the invited address (applyPendingInvites,
-- beside applyAutoJoin). One pending invite per (org, email).

CREATE TABLE org_invites (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  org_id      BIGINT NOT NULL REFERENCES orgs(id) ON DELETE CASCADE,
  email       TEXT   NOT NULL,
  org_role    TEXT   NOT NULL DEFAULT 'member' CHECK (org_role IN ('admin','member')),
  token_hash  TEXT   NOT NULL UNIQUE,
  invited_by  BIGINT REFERENCES users(id) ON DELETE SET NULL,
  created_at  TEXT   NOT NULL DEFAULT tela_now(),
  expires_at  TEXT   NOT NULL,
  accepted_at TEXT
);

CREATE INDEX idx_org_invites_email ON org_invites (lower(email));
CREATE INDEX idx_org_invites_org   ON org_invites (org_id);

-- At most one OUTSTANDING invite per (org, email); re-inviting refreshes that row.
CREATE UNIQUE INDEX uq_org_invites_pending
  ON org_invites (org_id, lower(email)) WHERE accepted_at IS NULL;
