-- 0064_selfhost_licenses.sql — self-serve self-host Enterprise licenses.
-- The CLOUD backend (the one with TELA_LICENSE_SIGNING_KEY set) mints a signed
-- offline ee license key when a buyer subscribes to the self-host Enterprise
-- Polar product (TELA_POLAR_SELFHOST_PRODUCT), stores it here, and emails it.
-- The buyer pastes the key into THEIR self-hosted instance (Settings → License),
-- which verifies it offline against the embedded public key — no phone-home.
-- Owner is the purchasing cloud user (checkout external_customer_id = user:<id>).
-- A renewal re-mints with a later expiry; a revoke marks the row and the key
-- simply lapses at its embedded expiry (offline keys can't be recalled).

CREATE TABLE selfhost_licenses (
  id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_user_id         BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  polar_subscription_id TEXT,
  polar_customer_id     TEXT,
  tier                  TEXT NOT NULL DEFAULT 'enterprise',
  seats                 INTEGER NOT NULL DEFAULT 0,        -- 0 = unspecified
  status                TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active','canceled','revoked')),
  token                 TEXT NOT NULL,                     -- the signed license key (re-minted on renewal)
  issued_at             TEXT NOT NULL DEFAULT tela_now(),
  expires_at            TEXT,                              -- NULL = perpetual (not used for subscriptions)
  created_at            TEXT NOT NULL DEFAULT tela_now(),
  updated_at            TEXT NOT NULL DEFAULT tela_now()
);

-- One row per Polar subscription (the reconciler upserts on it).
CREATE UNIQUE INDEX uq_selfhost_licenses_sub
  ON selfhost_licenses (polar_subscription_id) WHERE polar_subscription_id IS NOT NULL;
CREATE INDEX idx_selfhost_licenses_owner ON selfhost_licenses (owner_user_id);
