-- Feedback routing + Claude gating (issue-tracker phase 2a).
--
-- A feedback message now has an explicit recipient — a user or a GROUP of
-- users (first member to claim it responds) — instead of an implicit
-- instance-admin inbox; per-user permissions gate who may use the widget at
-- all and who may request an automated Claude triage; a single settings row
-- holds the composer's default target.

CREATE TABLE feedback_groups (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       TEXT NOT NULL UNIQUE CHECK (length(name) BETWEEN 1 AND 100),
  created_at TEXT NOT NULL DEFAULT tela_now()
);

CREATE TABLE feedback_group_members (
  group_id BIGINT NOT NULL REFERENCES feedback_groups(id) ON DELETE CASCADE,
  user_id  BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  PRIMARY KEY (group_id, user_id)
);

-- Missing row = enabled, no Claude (the widget stays on by default for
-- everyone; Claude triage is opt-in per user).
CREATE TABLE feedback_permissions (
  user_id      BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  enabled      INTEGER NOT NULL DEFAULT 1,
  allow_claude INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE feedback_settings (
  id               INTEGER PRIMARY KEY CHECK (id = 1),
  default_user_id  BIGINT REFERENCES users(id) ON DELETE SET NULL,
  default_group_id BIGINT REFERENCES feedback_groups(id) ON DELETE SET NULL
);
INSERT INTO feedback_settings (id) VALUES (1);

ALTER TABLE feedback
  ADD COLUMN recipient_user_id  BIGINT REFERENCES users(id) ON DELETE SET NULL,
  ADD COLUMN recipient_group_id BIGINT REFERENCES feedback_groups(id) ON DELETE SET NULL,
  ADD COLUMN claude_requested   INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN claimed_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  ADD COLUMN claimed_at         TEXT;
